### ISSUE TITLE
Remove SVG to PNG conversion.

### ISSUE THREAD

**Issue by kalyanov** [csstime/csstime-gulp-tasks#19]
[Microsoft stopped supporting older versions of Internet Explorer (IE10-)](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support). We can assume now that [SVG is supported](http://caniuse.com/#feat=svg) by all actual browsers and SVG to PNG conversion is redundant.

**Comment by jughosta** [comment]
Released in https://github.com/csstime/csstime-gulp-tasks/releases/tag/5.0.0
