### ISSUE TITLE
LESS or SASS syntax errors break gulp watch task

### ISSUE THREAD

**Issue by rdner** [csstime/csstime-gulp-tasks#23]
I'm using the [catberry-assets](https://github.com/catberry/catberry-assets) plugin which is based on css-time in the [catberry-hompage](https://github.com/catberry/catberry-homepage) project.

After I make a syntax error in any SASS file I see this message on the console:

```
[2016-03-30T10:34:01.929Z] [FATAL] [catberry:58560] – Error: catberry_components/pages/assets/sass/styles.scss
Error: property "min-height" must be followed by a ':'
        on line 2 of catberry_components/pages/assets/sass/styles.scss
>>  min-height. 100vh;
   -^

    at options.error (/Users/pragmadash/Projects/catberry-assets/node_modules/node-sass/lib/index.js:277:32)
```

And after that all styles stop rebuilding and I don't see any output on the console on changes.

Apparently, something causes an unhandled error because the logging level is `FATAL` and Catberry is not able to catch this error somehow and also the Gulp task stops watching after the error.

**Comment by jughosta** [comment]
Fixed in https://github.com/csstime/csstime-gulp-tasks/pull/25
