### ISSUE TITLE
Bug in minify-named-css.js 

### ISSUE THREAD

**Issue by reenko** [csstime/csstime-gulp-tasks#26]
When run task `minify-named-css` on `make release` in Catberry Framework we have a problem.

```
[TRACE] [catberry:36566] – Starting task csstime-handle-css...
[TRACE] [catberry:36566] – Task csstime-handle-css finished after 363 ms
[TRACE] [catberry:36566] – Starting task csstime-minify-css...
[FATAL] [catberry:36566] – undefined
```

**Cause:**
Valid LESS code
`font: 15px/@size-row @font-formular;` and `@size-row: 7 * @size-basis;`

**Comment by jughosta** [comment]
I am going to realize better error messages. Before that you can fix your code like this:

```
font: 15px/~`@{size-row}` @font-formular;
```

**Comment by reenko** [comment]
Thanks!
