### ISSUE TITLE
Question about bower components or npm modules

### ISSUE THREAD

**Issue by vizo** [csstime/csstime-gulp-tasks#29]
What would be best way to "include" assets of bower components or from npm modules.

For example i would like to add fonts from:
/bower_components/bootstrap-sass/assets/fonts/bootstrap

Is there any way to include them by some configuration or i need to copy them manually to some component assets folder every time package bootstrap-sass updates. I tried to make Symlink to folder but asset build fails.

Any idea?

Thanks.

**Comment by jughosta** [comment]
Hi,

If you need only styles from bower or npm package you can just add right import in your component's style file.

If not, there are 3 options:
1. store them in some `/vendor` dir inside `/static` or component's dir
2. copy fonts into `/static` or component's dir before every build process (ex. using your gulp task)
3. copy font direct to `/build` dir after every build process (ex. using your gulp task)

**Comment by vizo** [comment]
I think i will go with custom gulp task. How can include it into build process of csstime, where to put it?
I didn't find any documentation about this.

Thanks!

**Comment by jughosta** [comment]
You can insert a command in the package.json script https://github.com/catberry/catberry-todomvc/blob/develop/package.json#L36 or for a more complex case you can write your own plugin like this https://github.com/catberry/catberry-assets

**Comment by vizo** [comment]
Ok thanks!
