### ISSUE TITLE
Use autoprefixer v6

### ISSUE THREAD

**Issue by reenko** [csstime/csstime-gulp-tasks#32]
We have a problem with iPhone 6 and this problem is fixed in autoprefixer v6
https://github.com/postcss/autoprefixer/issues/495

Can csstime use v6?

**Comment by jughosta** [comment]
I guess we could use it, can you please create a PR?

**Comment by jughosta** [comment]
@reenko Please check this working version for your catberry project:
"catberry-assets": "catberry/catberry-assets#feature/csstime-upgrade-deps"

**Comment by reenko** [comment]
@JuliaRechkunova  Nice, but didn't fix problem with iPhone. :(
I think create task for autoprefixer.

**Comment by jughosta** [comment]
You mean there is still a bug in autoprefixer?

**Comment by jughosta** [comment]
@reenko Can we close this issue or it has to be addressed in `csstime`?

**Comment by reenko** [comment]
@JuliaRechkunova Yes, we can close this issue.
